### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by rajendrap123** [Laravel-Backpack/Generators#88]
# Bug report

D:\xampp\htdocs\aayo\aayowebapp>composer require phpoffice/phpspreadsheet --update-no-dev
You are running Composer with SSL/TLS protection disabled.
Using version ^1.13 for phpoffice/phpspreadsheet
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package backpack/generators (locked at v2.0.7, required as ^3.0) is satisfiable by backpack/generators[v2.0.7] but these conflict with your requirements or minimum-stability.

Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

Installation failed, reverting ./composer.json to its original content.

### What I did:

I tried to install PHPspreadsheet and its giving me this error

### Backpack, Laravel, PHP, DB version:
Backpack: 4.1
PHP: 7.3

**Comment by rajendrap123** [comment]
@tabacitu can you pls have a quick look into this?

Thanks for the great package!

**Comment by tabacitu** [comment]
@rajendrap123 I see you're probably requiring `2.* as 3.0.0` - try requiring `3.*`, that should fix it for you. The 2.* thing was only needed while Backpack 4.1 was in beta.

Cheers!

**Comment by rajendrap123** [comment]
@tabacitu thanks for the reply

I did change the composer, but still getting the error

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2",
        "backpack/backupmanager": "^2.0",
        "backpack/crud": "4.1.*",
        "backpack/filemanager": "^1.0",
        "backpack/logmanager": "^4.0.0",
        "backpack/pagemanager": "^3.0.0",
        "backpack/permissionmanager": "^6.0.0",
        "backpack/revise-operation": "^1.0",
        "backpack/settings": "^3.0",
        "baklysystems/laravel-chat-messenger": "^1.7",
        "barryvdh/laravel-dompdf": "^0.8.6",
        "barryvdh/laravel-elfinder": "^0.4.4",
        "benwilkins/laravel-fcm-notification": "^4.0",
        "beyondcode/laravel-comments": "^1.1",
        "consoletvs/charts": "^6.5",
        "fideloper/proxy": "^4.0",
        "intervention/image": "^2.3",
        "jeroennoten/laravel-adminlte": "^3.0",
        "laravel/framework": "^6.2",
        "laravel/helpers": "^1.1",
        "laravel/tinker": "^2.0",
        "laraveldaily/laravel-charts": "^0.1.13",
        "maatwebsite/excel": "^3.1",
        "paragraf-lex/viber-bot": "^0.0.7",
        "pusher/pusher-php-server": "^4.1",
        "qoraiche/laravel-mail-editor": "^2.0",
        "spatie/laravel-schemaless-attributes": "^1.6"
    },
    "require-dev": {
        "backpack/generators": "3.*",
        "facade/ignition": "^1.4",
        "fzaninotto/faker": "^1.4",
        "laracasts/generators": "^1.1",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^8.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
`

Here is my composer, do i missing something?

Thanks

**Comment by tabacitu** [comment]
Copy-paste the error please?

**Comment by rajendrap123** [comment]
@tabacitu thanks for the reply

below is the error:

`D:\xampp\htdocs\aayo\aayowebapp>composer require phpoffice/phpspreadsheet
You are running Composer with SSL/TLS protection disabled.
Using version ^1.13 for phpoffice/phpspreadsheet
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package backpack/generators (locked at v2.0.7, required as 3.*) is satisfiable by backpack/generators[v2.0.7] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.`

**Comment by tabacitu** [comment]
Looks like you haven't run `composer update` after updating the `composer.json`?

**Comment by rajendrap123** [comment]
@tabacitu thanks, it worked.

Very thank you
